name: scrobbler_bluos_monitor
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  clock: ^1.1.0
  http: ^1.1.0
  logging: ^1.0.2
  xml: ^6.0.1

dev_dependencies:
  fake_async: ^1.3.0
  lints:
  test:
