name: scrobbler
description: The Record Scrobbler Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.3+14

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  http: ^0.13.4
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  package_info: ^2.0.2
  logging: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  diacritic: ^0.1.1
  rate_my_app: ^1.1.2
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_performance: ^0.8.0+7

dev_dependencies:
  test:
  mockito: ^5.1.0
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons:
  effective_dart:
  #screenshots:
  #path_provider_platform_interface: ^1.0.1
  #plugin_platform_interface: ^1.0.2
  #file: ^5.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/discogs_logo.png
    - assets/discogs_logo_white.png
    - assets/empty_error.png
    - assets/empty_home.png
    - assets/empty_nothing.png
    - assets/empty_playlist.png
    - assets/empty_search.png
    - assets/lastfm_logo.png
    - assets/logo.svg
    - assets/record_sleeve.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
