name: scrobbler
description: The Scrobbler flutter application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+18

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.0
  crypto: ^3.0.1
  diacritic: ^0.1.1
  firebase_analytics: ^10.0.7
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_performance: ^0.9.0+7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_svg: ^2.0.0+1
  http: ^1.1.0
  in_app_review: ^2.0.4
  logging: ^1.0.2
  multicast_dns: ^0.3.2
  package_info_plus: ^4.1.0
  provider: ^6.0.2
  scrobbler_bluos_monitor:
    path: ../pkgs/bluos_monitor
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.1

dev_dependencies:
  build_runner:
  emulators:
  fake_async:
  file:
  flutter_driver:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito:
  #screenshots:
  test:

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/bluos_logo.png
    - assets/bluos_small.png
    - assets/discogs_logo.png
    - assets/discogs_logo_white.png
    - assets/empty_error.png
    - assets/empty_home.png
    - assets/empty_nothing.png
    - assets/empty_playlist.png
    - assets/empty_search.png
    - assets/lastfm_logo.png
    - assets/logo.svg
    - assets/record_sleeve.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
