name: scrobbler_bluos_monitor_server
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.0.2
  scrobbler_bluos_monitor:
    path: ../bluos_monitor
  shelf: ^1.2.0
  shelf_router: ^1.0.0

dev_dependencies:
  http:
  lints:
  test:
  test_process:
